version: "3.8"

services:
  vue-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "8080:8080"
    volumes:
      - ./src:/app/src:delegated
      - ./public:/app/public:delegated
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true
    tty: true

  vue-prod:
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - "80:80"
